name: Modified build
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - '21'
    name: build (${{ matrix.java }})
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: liberica
          cache: maven
      - run: sudo apt-get install xvfb
      - run: sudo apt-get install gettext
      - name: Build with Maven
        run: xvfb-run mvn -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true
          -Dprism.order=sw --batch-mode --update-snapshots verify "-Dsurefire.useFile=false"
          "-Dsurefire.reportsDirectory=" "-Dmaven.test.skip=true" "-Dsurefire.reportsDirectory=target/surefire-reports-dummy"
          "-Dmaven.compiler.generateTestSources=false" "-Dmaven.compiler.skip=true"
          "-Dmaven.surefire.reports.skip=true" "-Dtest.compile.skip=true" "-DskipTests=false"
          "-Dsurefire.reportFormat=plain" "-Dsurefire.reportFormat=xml" "-Dsurefire.reportEncoding=UTF-8"
          "-Dsurefire.skip=true" "-Dsurefire.skip=false" "-Dsurefire.redirectTestOutputToFile=false"
'on':
  - push
  - workflow_dispatch
